apiVersion: v2
name: hello-world
description: A Helm chart for Hello World application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - hello-world
  - web
  - nginx
home: https://github.com/example/hello-world
sources:
  - https://github.com/example/hello-world
maintainers:
  - name: DevOps Team
    email: devops@example.com 