# Default values for hello-world
# This is a YAML-formatted file.

# Application configuration
app:
  name: hello-world
  version: "1.0.0"

# Image configuration
image:
  repository: busybox
  tag: "1.35"
  pullPolicy: IfNotPresent

# Container configuration
container:
  port: 8080
  name: hello-world

# Environment configuration
environment:
  name: "base"
  logLevel: "info"
  debugEnabled: false

# Deployment configuration
deployment:
  replicas: 1
  strategy:
    type: Recreate

# Resource configuration
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Route configuration
route:
  enabled: true
  annotations: {}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

# Horizontal Pod Autoscaler configuration
hpa:
  enabled: false

# Security configuration
# Note: Security context is managed by OpenShift SCCs at the namespace level

# Health checks configuration
healthChecks:
  livenessProbe:
    enabled: true
    path: /
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    enabled: true
    path: /
    port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    scrape: true
    port: 8080
    path: /metrics

# Labels and annotations
labels:
  app: hello-world
  version: v1.0.0
  managed-by: helm

annotations:
  app.kubernetes.io/name: hello-world
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: helm
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

# Service account configuration
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Namespace configuration
namespace:
  create: false
  name: default 