# Staging environment values
environment:
  name: "staging"
  logLevel: "info"
  debugEnabled: false

deployment:
  replicas: 1

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 750m
    memory: 768Mi

hpa:
  enabled: false

route:
  enabled: true

labels:
  environment: staging
  tier: staging

annotations:
  environment: staging
  managed-by: argocd 