# Production environment values
environment:
  name: "prod"
  logLevel: "warn"
  debugEnabled: false

deployment:
  replicas: 1

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

hpa:
  enabled: false

route:
  enabled: true

labels:
  environment: prod
  tier: production

annotations:
  environment: prod
  managed-by: argocd 