# Production environment values
environment:
  name: "prod"
  logLevel: "warn"
  debugEnabled: false

deployment:
  replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: false

route:
  enabled: true

labels:
  environment: prod
  tier: production

annotations:
  environment: prod
  managed-by: argocd 