# Staging environment values
environment:
  name: "staging"
  logLevel: "info"
  debugEnabled: false

deployment:
  replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: false

route:
  enabled: true

labels:
  environment: staging
  tier: staging

annotations:
  environment: staging
  managed-by: argocd 