# Development environment values
environment:
  name: "dev"
  logLevel: "debug"
  debugEnabled: true

deployment:
  replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 384Mi

hpa:
  enabled: false

route:
  enabled: true

labels:
  environment: dev
  tier: development

annotations:
  environment: dev
  managed-by: argocd 