apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-hello-world-helm
  namespace: argocd
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: dev-helm
    environment: dev
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/argocd-repo-server
    targetRevision: HEAD
    chart: config/helm/hello-world
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 