apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hello-world-helm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: prod-helm
    environment: prod
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/argocd-repo-server
    targetRevision: main
    path: config/helm/hello-world
    helm:
      valueFiles:
      - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 