apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-hello-world-helm
  namespace: argocd
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: staging-helm
    environment: staging
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/argocd-repo-server
    targetRevision: HEAD
    path: config/helm/hello-world
    helm:
      valueFiles:
      - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 