apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-root-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: hello-world-root
    app.kubernetes.io/instance: root
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/argocd-repo-server
    targetRevision: HEAD
    path: argocd/apps-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 