apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-hello-world
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: prod
    environment: prod
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/argocd-repo-server
    targetRevision: HEAD
    path: config/kustomize/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 