apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hello-world-dev

namespace: dev

resources:
  - ../../base
  - configmap.yaml

patchesStrategicMerge:
  - patches/replica-count.yaml

namePrefix: dev-

commonLabels:
  environment: dev
  tier: development

commonAnnotations:
  environment: dev
  managed-by: argocd 