apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hello-world-dev

namespace: dev

resources:
  - ../../base
  - configmap.yaml

patches:
  - path: patches/replica-count.yaml
    target:
      kind: Deployment

namePrefix: dev-

labels:
  - pairs:
      environment: dev
      tier: development

commonAnnotations:
  environment: dev
  managed-by: argocd 