apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  labels:
    app: hello-world
    environment: staging
data:
  environment: "staging"
  log_level: "info"
  app_name: "hello-world"
  version: "v1.0.0"
  debug_enabled: "false" 