apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hello-world-staging

namespace: staging

resources:
  - ../../base
  - configmap.yaml

patches:
  - path: patches/replica-count.yaml
    target:
      kind: Deployment

namePrefix: staging-

labels:
  - pairs:
      environment: staging
      tier: staging

commonAnnotations:
  environment: staging
  managed-by: argocd 