apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hello-world-staging

namespace: staging

resources:
  - ../../base
  - configmap.yaml

patchesStrategicMerge:
  - patches/replica-count.yaml

namePrefix: staging-

commonLabels:
  environment: staging
  tier: staging

commonAnnotations:
  environment: staging
  managed-by: argocd 