apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  labels:
    app: hello-world
data:
  environment: "base"
  log_level: "info"
  app_name: "hello-world"
  version: "v1.1.0"
  deployment_method: "kustomize"
  last_updated: "2025-07-31" 