apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: hello-world
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      # Disable access logs to avoid file system issues
      access_log off;
      error_log /dev/stderr;
      
      # Disable client body temp files
      client_body_temp_path /tmp;
      client_max_body_size 0;
      
      server {
        listen 80;
        
        # Disable nginx default locations
        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }
        
        location / {
          return 200 'Hello World from OpenShift!\n';
          add_header Content-Type text/plain;
        }
        
        location /health {
          return 200 'OK\n';
          add_header Content-Type text/plain;
        }
      }
    } 