apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: hello-world
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          return 200 'Hello World from OpenShift!\n';
          add_header Content-Type text/plain;
        }
        location /health {
          return 200 'OK\n';
          add_header Content-Type text/plain;
        }
      }
    } 